### ISSUE TITLE
Unable to delete the index of a DataTable Row from a DataGridView.SelectedRows Table

### ISSUE THREAD

**Issue by codeliger** [codeliger/timelord#3]
http://stackoverflow.com/questions/37977975/how-do-i-get-the-relative-index-of-datagridview-selectedrows-into-datatable-rows

I can't figure out how to delete a value from a datagrid view if the datagrid view is not databound to a datatable, because the SelecedRows table has different array indexes than the DataTable.

To continue feature #2 we need a solution to this problem.

**Comment by ultrasaber** [comment]
Did you push a commit with an implementation yet? It'll help me better understand the problem.

**Comment by codeliger** [comment]
I commited it to master.

**Comment by rensoftworks** [comment]
The exception being thrown isn't related to array indexes; it's a concurrency exception coming from attempting to save changes made to the dataset. I've made some modifications to the for loop and added the AcceptChanges() method at the end of the loop.

This prevents the original exception from happening, and the changes are reflected in the form's dataset and DataGridView, but changes are not being saved to the SQLite file. I've done some research and it seems to be related to [connection state](https://social.msdn.microsoft.com/Forums/en-US/db906df0-c1c3-4554-ac03-dfe1aca7cf92/cant-update-sqlite-with-dataadapter-when-deleting-rows-in-datagridview-in-c?forum=adodotnetdataset), but I don't think that's the case for this particular problem. I'd look into exactly how task data is moved from the dataset into the SQLite file.
